//import activity list
//response is a responseObj generated by the quiz
//this will check the activity type and response type(positive, neutral negative)
//and add points to those types
// sort the array based on highest obj num
// then pick the higher scored items first to build activityCards for
// maximum of 6 activity cards per day in schedule (3 food, 3 other)


function readResponse(response){
   //this function returns a map with all types and a numeric value.
   //higher means the user likes the type more
   console.log('readResponse fired')
   let typeMap = new Map;
   typeMap.set('japanese', 0);
   typeMap.set('history', 0);
   typeMap.set('art', 0);
   typeMap.set('spicy', 0);
  


   for (let i = 0; i < response.length; i++){
      let thisType = response[i].type;
      console.log('thistype is ' + thisType);
     
      let currentVal = typeMap.get(thisType);
      if (response[i].response == 'positive'){
         currentVal = currentVal+1;
      }
      else if (response[i].response == 'negative'){
         currentVal = currentVal - 1;
      }
      else if (response[i].response == 'neutral'){
         currentVal = currentVal;
      }
      typeMap.set(thisType, currentVal);
      console.log(thisType + "=" + typeMap.get(thisType))
   }
   return typeMap;

}

module.exports = {readResponse}