//import activity list
//response is a responseObj generated by the quiz
//this will check the activity type and response type(positive, neutral negative)
//and add points to those types
// sort the array based on highest obj num
// then pick the higher scored items first to build activityCards for
// maximum of 6 activity cards per day in schedule (3 food, 3 other)


function readResponse(response){
   //this function returns a map with all types and a numeric value.
   //higher means the user likes the type more
   console.log('readResponse fired')
   let typeMap = new Map;
   typeMap.set('japanese', 0);
   typeMap.set('history', 0);
   typeMap.set('art', 0);
   typeMap.set('spicy', 0);
  


   for (let i = 0; i < response.length; i++){
      let thisType = response[i].type;
      console.log('thistype is ' + thisType);
     
      let currentVal = typeMap.get(thisType);
      if (response[i].response == 'positive'){
         currentVal = currentVal+1;
      }
      else if (response[i].response == 'negative'){
         currentVal = currentVal - 1;
      }
      else if (response[i].response == 'neutral'){
         currentVal = currentVal;
      }
      typeMap.set(thisType, currentVal);
      console.log(thisType + "=" + typeMap.get(thisType))
   }
   return typeMap;

}

function buildItineraryActivities(typeMap){
   //this read each value in the map and check if its value is above 0. Only recommend activities that are
   //over 0.

   //it will return an array of activity Objects
   let activityArr;
   


   return activityArr;
}

function buildDailySchedule(activityArr) {
   //this function will check how close the activities are.
   //and will place activity cards into days 
   //then build the component with the completed information (date and activity object)
   //and return them in an array.
   
}

function getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) {
   //from stackoverflow. use this to calculate the distance between different activities.
   
   var R = 6371; // Radius of the earth in km
   var dLat = deg2rad(lat2-lat1);  // deg2rad below
   var dLon = deg2rad(lon2-lon1); 
   var a = 
     Math.sin(dLat/2) * Math.sin(dLat/2) +
     Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * 
     Math.sin(dLon/2) * Math.sin(dLon/2)
     ; 
   var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); 
   var d = R * c; // Distance in km
   return d;
 }
 
 function deg2rad(deg) {
   return deg * (Math.PI/180)
 }

module.exports = {readResponse}